### ISSUE TITLE
MEF reader in Python

### ISSUE THREAD

**Issue by agramfort** [ieeg-portal/ieegpy#1]
hi,

not sure if it's the right place to ask but is there a Python reader for MEF files?

thanks

**Comment by joacorapela** [comment]
I tried to use the code in ieegpy to read data from the ieeg portal. The code has a small bug and does not run (line 21, hbt_dataset.py, tsd is not defined). After fixing this bug I noticed that the functionality of the code is wrong (I requested 10 seconds of data and got only one value).

**Comment by zackives** [comment]
(Fix after joining project: added sample code + docs, showing that time is in usec and not sec.)
