### ISSUE TITLE
ModuleNotFoundError: No module named 'mprov'

### ISSUE THREAD

**Issue by BenDing96** [ieeg-portal/ieegpy#3]
I couldn't find this module, I don't know how to download it or add to my path.

**Comment by BenDing96** [comment]
when I run "python read_sample.py myid password "

**Comment by jfromme** [comment]
Thanks for the report.

I have fixed the imports to use the correct package (pennprov, not mprov) and updated the README to include that package in the list of dependencies that need to be installed with pip.
