### ISSUE TITLE
'Authorization failed or cannot find study I004_A0003_D001'

### ISSUE THREAD

**Issue by ghost** [ieeg-portal/ieegpy#7]
Hi.
I'm trying to use the following code on a windows 7 machine with python 3.7.4 to open a dataset:
```python
import sys
from ieeg.auth import Session
from ieeg.processing import ProcessSlidingWindowPerChannel, ProcessSlidingWindowAcrossChannels
from pennprov.connection.mprov_connection import MProvConnection
import numpy as np
username = 'xxx' # Same username and password works on ieeg.org and with the Matlab toolbox
password = 'xxx'
with Session(username,password) as s:
    ds = s.open_dataset('I004_A0003_D001')
```
I receive the following error:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IeegWsException><errorCode>AuthenticationFailureSigExpired</errorCode><errorId>98aaf85e-a681-40e1-a521-06e8da55c94c</errorId><hostname>ip-10-0-0-145</hostname><message>The server responded with 403 Forbidden. If reporting the error please include the following: Error code: [AuthenticationFailureSigExpired], Error message: [Access Denied], host: [ip-10-0-0-145], error id: [98aaf85e-a681-40e1-a521-06e8da55c94c].</message></IeegWsException>
---------------------------------------------------------------------------
IeegConnectionError                       Traceback (most recent call last)
<ipython-input-38-b64c434f0921> in <module>
      9 
     10 with Session(username,password) as s:
---> 11     ds = s.open_dataset('I004_A0003_D001')

C:\ProgramData\Anaconda3\lib\site-packages\ieeg-1.4.1-py3.7.egg\ieeg\auth.py in open_dataset(self, name)
     91             print(get_id_response.text)
     92             raise IeegConnectionError(
---> 93                 'Authorization failed or cannot find study ' + name)
     94 
     95         snapshot_id = get_id_response.text

IeegConnectionError: 'Authorization failed or cannot find study I004_A0003_D001'
```

Accessing the API URL `https://www.ieeg.org/services/timeseries/getIdByDataSnapshotName/I004_A0003_D001` directly throws a 500 internal server error message, so not sure if it's me, the tool or the API?

**Comment by jfromme** [comment]
Both the Matlab and Python clients automatically include a timestamp in the request headers. The error code`AuthenticationFailureSigExpired` indicates that when the server received your request the timestamp contained in the request was either in the future or more than 15 minutes in the past.

Is it possible that the clock on your Windows machine is not set to the current time?

**Comment by ghost** [comment]
I believe it's correctly set, given that I can access the datasets using the Matlab client.
However, I'm probably in a different time zone (GMT+1) than the server.
Could this be the source of the problem?

**Comment by jfromme** [comment]
Yes, you're absolutely correct. Our timestamp string did not include timezone information. Please try the latest version (1.4.2) which should correct this.

**Comment by ghost** [comment]
Works like a charm. Thanks John!

**Comment by jfromme** [comment]
Great, thanks for your help!
